server:
  port: 8081

spring:
  application:
    name: eshop-cache
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/zc
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
    cluster:
      nodes:
        - 192.168.56.110:7001
        - 192.168.56.110:7002
        - 192.168.56.120:7003
        - 192.168.56.120:7004
        - 192.168.56.130:7005
        - 192.168.56.130:7006
    database: 0
    lettuce:
      pool:
        max-wait: -1
        max-idle: 10
        max-active: 100
        min-idle: 5