server:
  port: 8080

spring:
  application:
    name: eshop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/zc
    username: root
    password: root


  redis:
    timeout: 6000ms
    database: 0
    cluster:
      nodes:
        - 192.168.56.110:7001
        - 192.168.56.110:7002
        - 192.168.56.120:7003
        - 192.168.56.120:7004
        - 192.168.56.130:7005
        - 192.168.56.130:7006
      max-redirects: 3 # 获取失败最大的重定向次数
    lettuce:
      pool:
        max-active: 100 # 连接池的最大链接树 ，负数未没有限制
        max-idle: 10 # 连接池中最大的空闲链接
        min-idle: 5 # 最小空闲链接
        max-wait: -1 # 连接池最大的阻塞等待时间 负数表示没有限制